[package]
name = "zc"
version = "0.1.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
clap = { version = "3.0.10", features = ["derive"] }
zip = "0.5.13"
